modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "missions"
version = "${version}"
displayName = "Missions"
authors = "MrRedRhino, MuriPlz"
description = '''
Missions here and there :P
'''
#logoFile = ""

[[dependencies.missions]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.missions]]
modId="create"
mandatory=true
versionRange="[0.5.1.c,)"
ordering="NONE"
side="BOTH"
